export const GET_COMPANIES = 'COMPANY/GET_COMPANIES';
export const GET_COMPANIES_SUCCESS = 'COMPANY/GET_COMPANIES_SUCCESS';

export const GET_DEMO_COMPANIES = 'COMPANY/GET_DEMO_COMPANIES';
export const GET_DEMO_COMPANIES_SUCCESS = 'COMPANY/GET_DEMO_COMPANIES_SUCCESS';

export const GET_COMPANY_DETAILS = 'COMPANY/GET_COMPANY_DETAILS';
export const GET_COMPANY_DETAILS_SUCCESS =
  'COMPANY/GET_COMPANY_DETAILS_SUCCESS';

export const GET_COMPANY_SETUPINFO = 'COMPANY/GET_COMPANY_SETUPINFO';
export const GET_COMPANY_SETUPINFO_SUCCESS =
  'COMPANY/GET_COMPANY_SETUPINFO_SUCCESS';

export const CREATE_COMPANY = 'COMPANY/CREATE_COMPANY';
export const CREATE_COMPANY_SUCCESS = 'COMPANY/CREATE_COMPANY_SUCCESS';

export const CREATE_MESSAGE_WORKER_PLATFORM =
  'COMPANY/CREATE_MESSAGE_WORKER_PLATFORM';
export const CREATE_MESSAGE_WORKER_PLATFORM_SUCCESS =
  'COMPANY/CREATE_MESSAGE_WORKER_PLATFORM_SUCCESS';

export const GET_COMPANY_PRIMARY_ADMINS = 'COMPANY/GET_COMPANY_PRIMARY_ADMINS';
export const GET_COMPANY_PRIMARY_ADMINS_SUCCESS =
  'COMPANY/GET_COMPANY_PRIMARY_ADMINS_SUCCESS';

export const GET_COMPANY_ADMINS = 'COMPANY/GET_COMPANY_ADMINS';
export const GET_COMPANY_ADMINS_SUCCESS = 'COMPANY/GET_COMPANY_ADMINS_SUCCESS';

export const GET_COMPANY_MANAGERS = 'COMPANY/GET_COMPANY_MANAGERS';
export const GET_COMPANY_MANAGERS_SUCCESS =
  'COMPANY/GET_COMPANY_MANAGERS_SUCCESS';

export const GET_COMPANY_SURVEYS = 'COMPANY/GET_COMPANY_SURVEYS';
export const GET_COMPANY_SURVEYS_SUCCESS =
  'COMPANY/GET_COMPANY_SURVEYS_SUCCESS';

export const UPDATE_COMPANY_SURVEYS = 'COMPANY/UPDATE_COMPANY_SURVEYS';
export const UPDATE_COMPANY_SURVEYS_SUCCESS =
  'COMPANY/UPDATE_COMPANY_SURVEYS_SUCCESS';

export const GET_MODULE_PERMISSION = 'COMPANY/GET_MODULE_PERMISSION';
export const GET_MODULE_PERMISSION_SUCCESS =
  'COMPANY/GET_MODULE_PERMISSION_SUCCESS';

export const UPDATE_MODULE_PERMISSIONS = 'COMPANY/UPDATE_MODULE_PERMISSIONS';
export const UPDATE_MODULE_PERMISSIONS_SUCCESS =
  'COMPANY/UPDATE_MODULE_PERMISSIONS_SUCCESS';
