export const GET_COUNTRIES = 'COMPANY/GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'COMPANY/GET_COUNTRIES_SUCCESS';

export const GET_PACKAGES = 'COMPANY/GET_PACKAGES';
export const GET_PACKAGES_SUCCESS = 'COMPANY/GET_PACKAGES_SUCCESS';

export const GET_COURIERS = 'COMPANY/GET_COURIERS';
export const GET_COURIERS_SUCCESS = 'COMPANY/GET_COURIERS_SUCCESS';

export const GET_LANGUAGES = 'COMPANY/GET_LANGUAGES';
export const GET_LANGUAGES_SUCCESS = 'COMPANY/GET_LANGUAGES_SUCCESS';

export const GET_COMPANIES = 'COMPANY/GET_COMPANIES';
export const GET_COMPANIES_SUCCESS = 'COMPANY/GET_COMPANIES_SUCCESS';

export const GET_COMPANY_DETAILS = 'COMPANY/GET_COMPANY_DETAILS';
export const GET_COMPANY_DETAILS_SUCCESS =
  'COMPANY/GET_COMPANY_DETAILS_SUCCESS';

export const GET_COMPANY_SETUPINFO = 'COMPANY/GET_COMPANY_SETUPINFO';
export const GET_COMPANY_SETUPINFO_SUCCESS =
  'COMPANY/GET_COMPANY_SETUPINFO_SUCCESS';

export const CREATE_COMPANY = 'COMPANY/CREATE_COMPANY';
export const CREATE_COMPANY_SUCCESS = 'COMPANY/CREATE_COMPANY_SUCCESS';

export const CREATE_MESSAGE_WORKER_PLATFORM =
  'COMPANY/CREATE_MESSAGE_WORKER_PLATFORM';
export const CREATE_MESSAGE_WORKER_PLATFORM_SUCCESS =
  'COMPANY/CREATE_MESSAGE_WORKER_PLATFORM_SUCCESS';

export const GET_COMPANY_PRIMARY_ADMINS = 'COMPANY/GET_COMPANY_PRIMARY_ADMINS';
export const GET_COMPANY_PRIMARY_ADMINS_SUCCESS =
  'COMPANY/GET_COMPANY_PRIMARY_ADMINS_SUCCESS';

export const GET_COMPANY_ADMINS = 'COMPANY/GET_COMPANY_ADMINS';
export const GET_COMPANY_ADMINS_SUCCESS = 'COMPANY/GET_COMPANY_ADMINS_SUCCESS';

export const GET_COMPANY_MANAGERS = 'COMPANY/GET_COMPANY_MANAGERS';
export const GET_COMPANY_MANAGERS_SUCCESS =
  'COMPANY/GET_COMPANY_MANAGERS_SUCCESS';

export const GET_COMPANY_SURVEYS = 'COMPANY/GET_COMPANY_SURVEYS';
export const GET_COMPANY_SURVEYS_SUCCESS =
  'COMPANY/GET_COMPANY_SURVEYS_SUCCESS';

export const UPDATE_COMPANY_SURVEYS = 'COMPANY/UPDATE_COMPANY_SURVEYS';
export const UPDATE_COMPANY_SURVEYS_SUCCESS =
  'COMPANY/UPDATE_COMPANY_SURVEYS_SUCCESS';

export const GET_COMPANY_SUBSCRIPTIONS = 'COMPANY/GET_COMPANY_SUBSCRIPTIONS';
export const GET_COMPANY_SUBSCRIPTIONS_SUCCESS =
  'COMPANY/GET_COMPANY_SUBSCRIPTIONS_SUCCESS';

export const UPDATE_MODULE_PERMISSIONS = 'COMPANY/UPDATE_MODULE_PERMISSIONS';
export const UPDATE_MODULE_PERMISSIONS_SUCCESS =
  'COMPANY/UPDATE_MODULE_PERMISSIONS_SUCCESS';
