export const GET_SURVEY_TEMPLATES = 'SURVEY/GET_SURVEY_TEMPLATES';
export const GET_SURVEY_TEMPLATES_SUCCESS =
  'SURVEY/GET_SURVEY_TEMPLATES_SUCCESS';

export const GET_SURVEY_TEMPLATE = 'SURVEY/GET_SURVEY_TEMPLATE';
export const GET_SURVEY_TEMPLATE_SUCCESS = 'SURVEY/GET_SURVEY_TEMPLATE_SUCCESS';

export const GET_COMPANY_SURVEYS = 'SURVEY/GET_COMPANY_SURVEYS';
export const GET_COMPANY_SURVEYS_SUCCESS = 'SURVEY/GET_COMPANY_SURVEYS_SUCCESS';

export const CREATE_COMPANY_SURVEY_SCHEDULE =
  'SURVEY/CREATE_COMPANY_SURVEY_SCHEDULE';
export const CREATE_COMPANY_SURVEY_SCHEDULE_SUCCESS =
  'SURVEY/CREATE_COMPANY_SURVEY_SCHEDULE_SUCCESS';
