export const GET_SURVEY_TEMPLATES = 'SURVEY/GET_SURVEY_TEMPLATES';
export const GET_SURVEY_TEMPLATES_SUCCESS =
  'SURVEY/GET_SURVEY_TEMPLATES_SUCCESS';

export const GET_COMPANIES_FOR_SURVEY = 'SURVEY/GET_COMPANIES_FOR_SURVEY';
export const GET_COMPANIES_FOR_SURVEY_SUCCESS =
  'SURVEY/GET_COMPANIES_FOR_SURVEY_SUCCESS';

export const GET_SURVEY_TEMPLATE = 'SURVEY/GET_SURVEY_TEMPLATE';
export const GET_SURVEY_TEMPLATE_SUCCESS = 'SURVEY/GET_SURVEY_TEMPLATE_SUCCESS';

export const GET_COMPANY_SURVEYS = 'SURVEY/GET_COMPANY_SURVEYS';
export const GET_COMPANY_SURVEYS_SUCCESS = 'SURVEY/GET_COMPANY_SURVEYS_SUCCESS';

export const CREATE_COMPANY_SURVEY_SCHEDULE =
  'SURVEY/CREATE_COMPANY_SURVEY_SCHEDULE';
export const CREATE_COMPANY_SURVEY_SCHEDULE_SUCCESS =
  'SURVEY/CREATE_COMPANY_SURVEY_SCHEDULE_SUCCESS';

export const STORE_SURVEY_BASIC_INFO = 'SURVEY/STORE_SURVEY_BASIC_INFO';
export const SET_LAST_SURVEY_QUESTION = 'SURVEY/SET_LAST_SURVEY_QUESTION';
export const STORE_SURVEY_QUESTIONS = 'SURVEY/STORE_SURVEY_QUESTIONS';
export const UPDATE_SURVEY_QUESTIONS = 'SURVEY/UPDATE_SURVEY_QUESTIONS';
export const ADD_SURVEY_QUESTION = 'SURVEY/ADD_SURVEY_QUESTION';
export const DELETE_SURVEY_QUESTION = 'SURVEY/DELETE_SURVEY_QUESTION';
export const UPDATE_SURVEY_ANSWER = 'SURVEY/UPDATE_SURVEY_ANSWER';
export const ADD_SURVEY_ANSWER = 'SURVEY/ADD_SURVEY_ANSWER';
export const DELETE_SURVEY_ANSWER = 'SURVEY/DELETE_SURVEY_ANSWER';

export const CREATE_SURVEY_TEMPLATE = 'SURVEY/CREATE_SURVEY_TEMPLATE';
export const CREATE_SURVEY_TEMPLATE_SUCCESS =
  'SURVEY/CREATE_SURVEY_TEMPLATE_SUCCESS';
